// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ahygrsgsvqzruvslihws.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFoeWdyc2dzdnF6cnV2c2xpaHdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxMTI2NjAsImV4cCI6MjA3MDY4ODY2MH0.df_h1lMeWu_H6ddFxx478w-Six8nFwPHeCIxZvefKuA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});